### ISSUE TITLE
Nested drop targets: How to trigger isOverCurrent container AND isOver a child?

### ISSUE THREAD

**Issue by 3Cbwaltz** [gaearon/react-dnd#362] opened 2016-01-27 16:48 UTC
Hello,

I have a nested sortable setup and I want to utilize a placeholder when dragging to show where the user can place the item. I am running into a problem when trying to render the placeholder while the mouse is over the current drop container. What I want is to ONLY see the placeholder if the mouse is over the shallowest container AND over one of it's children. My code moves the placeholder before or after the child item based on (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2. 

Every time I use isOver to check whether to the mouse is over the current drop container, sometimes I get the placeholder in different two different parents (see image).

![Image of double placeholders]
(http://cl.ly/3z2j1Z460W3I/Screen%20Shot%202016-01-27%20at%2010.48.04%20AM%20(2).png)

Otherwise, if I use isOverCurrent (monitor.isOver({ shallow: true })), the parent container looses focus entirely when over a child. This makes the placeholder only display in the spacing in between child items. And if I have to do it this way, I would have to put more spacing around items, which makes it look pretty weird.

Do you have a suggestion on how to do this?

**Menu**
```
import React, { PropTypes, Component } from 'react'
import { DropTarget } from 'react-dnd'
import Item from './nodeItem'
import { ItemTypes } from './Constants';
import ReactDOM from 'react-dom';
import _ from 'lodash';
import $ from 'jquery';
import menuStyle from './menu.css';

import classNames from 'classnames';

const target = {
  drop(props, monitor, component) {
    const hasDroppedOnChild = monitor.didDrop();
    if (hasDroppedOnChild) {
      return;
    }
    props.drop(monitor.getItem(), component.state.placeholderPosition, props.parent);
    component._resetPlaceholder();
  },

  hover(props, monitor, component) {

    let height = monitor.getItem().height;

    component._changePlaceholderHeight(height);

    const {id: draggedId, parent, children} = monitor.getItem();

    if (!children){
        var children_check = [];
    }else{
        var children_check = children;
    }
  }

}

@DropTarget('ITEM', target, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver(),
  isOverCurrent: monitor.isOver({ shallow: true })
}))

export default class Menu extends Component {
    static propTypes = {
        children  : PropTypes.array,
        parent : PropTypes.any,
        drop   : PropTypes.func.isRequired,
        find   : PropTypes.func.isRequired,
        isOver: PropTypes.bool.isRequired,
        isOverCurrent: PropTypes.bool.isRequired,
        itemAttributes: PropTypes.any,
        itemDelete: PropTypes.func,
        itemRevert: PropTypes.func,
        itemEdit: PropTypes.func,
        itemRename: PropTypes.func,
        onItemActive: PropTypes.func,
        activeNode: PropTypes.any,
    };

    state = {
        placeholderPosition: 0,
        placeholderHeight: 50,
        activeNode: 0,
        renameNodes: [],
    };

    constructor(props) {
        super(props);
        this._movePlaceholderAfter = this._movePlaceholderAfter.bind(this);
        this._movePlaceholderBefore = this._movePlaceholderBefore.bind(this);
        this._resetPlaceholder = this._resetPlaceholder.bind(this);
        this._changePlaceholderHeight = this._changePlaceholderHeight.bind(this);
        this._scrollDragHeight = this._scrollDragHeight.bind(this);
        this.handleNodeRenaming = this.handleNodeRenaming.bind(this);
        this.renameRemove = this.renameRemove.bind(this);
        this.renameSubmit = this.renameSubmit.bind(this);
    }

    _movePlaceholderBefore(id){
        this.setState({
            placeholderPosition: id,
        });
    }

    _movePlaceholderAfter(id){

        let index = _.findIndex(this.props.children, {id: id});
        let next = this.props.children[index + 1];
        let placeholderPosition = next ? next.id : 0;

        this.setState({
            placeholderPosition: placeholderPosition,
        });
    }

    _resetPlaceholder(){
        this.setState({placeholderPosition: 0});
    }

    _changePlaceholderHeight(height) {
        this.setState({
            placeholderHeight: height,
        });
    }

    _scrollDragHeight(height){
        //handle scrolling to end of container
        this.refs.courseOutline.scrollTop += $(this.refs.courseOutline)[0].scrollHeight;
    }

    handleNodeRenaming(renameItem){
        if(_.isEmpty(this.state.renameNodes) || !$.inArray(renameItem.id, this.state.renameNodes)){
            let newRenameNodes = _.cloneDeep(this.state.renameNodes);
            newRenameNodes.push(renameItem.id);

            this.setState({
                renameNodes: newRenameNodes
            });
        }
    }

    renameRemove(renameItem){
        let newRenameNodes = _.cloneDeep(this.state.renameNodes);
        newRenameNodes = _.pull(newRenameNodes, renameItem.id);
        this.setState({
            renameNodes: newRenameNodes
        });
    }

    renameSubmit(renameItem, newTitle){
        this.renameRemove(renameItem);
        this.props.itemRename(renameItem, newTitle);
    }

  render() {
    const {
        connectDropTarget, 
        children, 
        parent, 
        drop, 
        find, 
        isOver,
        isOverCurrent,
        itemAttributes,
        itemDelete,
        itemRevert,
        itemEdit,
        itemRename,
        onItemActive,
        collapsed,
        activeNode
    } = this.props



    if(collapsed){
        return (<div></div>);
    }

    if(children && !_.isEmpty(children)){
        var items = [];
        var i = 1;
        this.props.children.forEach(function(item) {


            if(isOverCurrent && item.id === this.state.placeholderPosition){
                items.push(<li className={menuStyle.placeholder} style={{height: this.state.placeholderHeight}} key="placeholder"></li>);
            }

            let active = item.id == activeNode.id ? true : false;

            items.push(
                <Item
                    //new
                    key={item.id}
                    id={item.id}
                    item={item}

                    //props
                    parent={parent}
                    drop={drop}
                    find={find}

                    itemAttributes={itemAttributes} 
                    onDelete={itemDelete}
                    onDeleteRevert={itemRevert}
                    onEdit={itemEdit}
                    itemRename={itemRename}
                    onItemActive={onItemActive}
                    activeNode={activeNode}

                    index={i}
                    onRenameSubmit={this.renameSubmit}
                    onRenameCancel={this.renameRemove}
                    onRenaming={this.handleNodeRenaming}
                    active={active}
                    movePlaceholderBefore={this._movePlaceholderBefore}
                    movePlaceholderAfter={this._movePlaceholderAfter}

                  />
            );

            i++;
        }.bind(this));

        if (isOverCurrent && this.state.placeholderPosition === 0) {
            items.push(<li className={menuStyle.placeholder} style={{height: this.state.placeholderHeight}} key="placeholder"></li>);
        }
    }else{
        var items = [];
        if (isOverCurrent && this.state.placeholderPosition === 0) {
            items.push(<li className={menuStyle.placeholder} style={{height: this.state.placeholderHeight}} key="placeholder"></li>);
        }
        
    }

    let style = {
        paddingTop: "10px"
    };
    
    if(isOverCurrent){
        style.backgroundColor = "#A6A4A4";
        if(children && !_.isEmpty(children)){
            style.paddingBottom = "10px";
        }else{
            style.paddingTop = "5px";
        }
    }

      //class names
    var menuClassName = classNames('list-group', menuStyle.menu);
    var headerClassName = classNames(menuStyle.menuHeader, this.props.headerClass);

    if(!_.isEmpty(this.state.renameNodes)){
        return (
            <ul style={style} className={menuClassName} data-nodeid={parent} >
                {items}
            </ul>  
        )
    }else{
        return connectDropTarget(
            <ul style={style} className={menuClassName} data-nodeid={parent} >
                {items}
            </ul>
        )
    }
  }
}
```

**Item**
```
import React, { PropTypes, Component } from 'react'
import { DragSource, DropTarget } from 'react-dnd'
import Menu from './menu'
import { ItemTypes } from './Constants';
import ReactDOM from 'react-dom';
import _ from 'lodash';
import $ from 'jquery';
import ClickButton from 'cccisd-click-button';
import nodeStyle from './nodeItem.css';

const source = {
  beginDrag(props, monitor, component) {

    return {
      id: props.id,
      parent: props.parent,
      outline_title: props.item.outline_title,
      children: props.item.children,
      title: props.item.title,
      type: props.item.type,
      deleted: props.item.deleted,
      new: props.item.new,
      height: ReactDOM.findDOMNode(component).offsetHeight
    }
  },

  isDragging(props, monitor) {
    return props.id == monitor.getItem().id
  },

}

const target = {
  canDrop() {
    return false
  },

  hover(props, monitor, component) {

    if(monitor.isOver({ shallow: true })){ 
         // Determine rectangle on screen
        let hoverBoundingRect = ReactDOM.findDOMNode(component).getBoundingClientRect();

        // Get horizontal middle
        let hoverMiddleY = (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2;

        // Determine mouse position
        let clientOffset = monitor.getClientOffset();

        // Get pixels to the bottom
        let hoverClientY = hoverBoundingRect.bottom - clientOffset.y;
        
        
        if (hoverClientY > hoverMiddleY) {
            props.movePlaceholderBefore(props.item.id);
        } 
        else {
            props.movePlaceholderAfter(props.item.id);
        }
    }
    }
}

@DropTarget('ITEM', target, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver(),
  isOverCurrent: monitor.isOver({ shallow: true })
}))
@DragSource('ITEM', source, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  connectDragPreview: connect.dragPreview(),
  isDragging: monitor.isDragging()
}))
export default class Item extends Component {
    static propTypes = {
        id     : PropTypes.any.isRequired,
        parent : PropTypes.any,
        item   : PropTypes.object,
        find   : PropTypes.func,
        itemAttributes: PropTypes.any,
        itemDelete: PropTypes.func,
        itemRevert: PropTypes.func,
        itemEdit: PropTypes.func,
        itemRename: PropTypes.func,
        onItemActive: PropTypes.func,
        activeNode: PropTypes.any,
    };
    
    state = {
        isHovering: false,
        nodeTitleCopy: this.props.item.outline_title,
        nodeTitle: this.props.item.outline_title,
        editing: false,
        deleted: false,
        collapsed: (this.props.item.children && !_.isEmpty(this.props.item.children)) ? true : false,
    }

    constructor(props) {
        super(props);
        this.handleMouseOver = this.handleMouseOver.bind(this);
        this.handleMouseOut = this.handleMouseOut.bind(this);
        this._deleteButton = this._deleteButton.bind(this);
        this._revertButton = this._revertButton.bind(this);
        this._confirmEditButton = this._confirmEditButton.bind(this);
        this.onEditClick = this.onEditClick.bind(this);
        this.onDeleteClick = this.onDeleteClick.bind(this);
        this.onRevertClick = this.onRevertClick.bind(this);
        this.onChange = this.onChange.bind(this);
        this.enableRename = this.enableRename.bind(this);
        this.handleBlur = this.handleBlur.bind(this);
        this.getClickHandler = this.getClickHandler.bind(this);
        this.inputEscape = this.inputEscape.bind(this);
        this.onKey = this.onKey.bind(this);
        this.collapseExpand = this.collapseExpand.bind(this);
        this.addExpandCollapseBtn = this.addExpandCollapseBtn.bind(this);
    }

    handleMouseOver() {
        this.setState({ isHovering: true });
    }

    handleMouseOut() {
        this.setState({ isHovering: false });
    }

    _deleteButton(item){
        var className = "glyphicon glyphicon-remove";
        var item = this.props.item;
        return (
            <ClickButton
                title=''
                className={className}
                isConfirm={false}
                onClick={this.onDeleteClick.bind(this, item)}
            />
        );
    }

    _revertButton(item){
        var className = "glyphicon glyphicon-repeat";
        var item = this.props.item;
        return (
            <ClickButton
                title=''
                className={className}
                isConfirm={false}
                onClick={this.onRevertClick.bind(this, item)}
            />
        );
    }

    _confirmEditButton(item){
        var className = "glyphicon glyphicon-ok";
        var item = this.props.item;
        return (
            <ClickButton
                title=''
                className={className}
                isConfirm={false}
                onClick={this.handleBlur}
            />
        );
    }

    onEditClick(clickedItem){
        if(!this.state.editing){
            this.props.onEdit(clickedItem);
        }
    }

    onDeleteClick(clickedItem){
        this.setState({ deleted: true });
        this.props.onDelete(clickedItem);
    }

    onRevertClick(clickedItem){
        this.setState({ deleted: false });
        this.props.onDeleteRevert(clickedItem);
    }

    onChange(event) {
        this.setState({nodeTitle: event.target.value});
    }

    enableRename(){

        this.setState({ 
            editing: true,
            nodeTitleCopy: this.state.nodeTitle,
        });

        this.props.onRenaming(this.props.item);

    }

    handleBlur(){

        //only if title text has changed
        if(this.state.nodeTitleCopy != this.state.nodeTitle){

            //set editing true
            this.setState({ editing: false });

            this.props.onRenameSubmit(this.props.item, this.state.nodeTitle);
        }
        else{
            this.setState({ editing: false});
        }
    }

    getClickHandler(onClick, onDblClick, delay) {
        var timeoutID = null;
        delay = delay || 250;
        if (this.state.deleted){
            return false;
        }
        else{
            return function (event) {
                if (!timeoutID) {
                    timeoutID = setTimeout(function () {
                        onClick(event);
                        timeoutID = null
                    }, delay);
                } else {
                    timeoutID = clearTimeout(timeoutID);
                    onDblClick(event);
                }
            };
        }
    }

    inputEscape(){
        this.setState({
            nodeTitle: this.state.nodeTitleCopy,
            editing: false
        });

        this.props.onRenameCancel(this.props.item);
    }

    onKey(e){

        var key = e.keyCode;

        if(key == 13){
            //enter
            this.handleBlur();
        }
        else if(key == 27){
            //escape
            this.inputEscape(); 
        }
        
    }

    collapseExpand(){
        if(this.state.collapsed){
            this.setState({collapsed: false});
        }
        else{
            this.setState({collapsed: true});
        }
    }

    addExpandCollapseBtn(){
        if(this.state.collapsed){
            var collapsedClass = 'fa fa-plus-square-o';
        }
        else{
            var collapsedClass = 'fa fa-minus-square-o';
        }

        if(this.props.item.children && !_.isEmpty(this.props.item.children)){
            return (<div className={nodeStyle.expandBtn}><a style={{cursor: "pointer", textDecoration: "none", color: "black"}} onClick={this.collapseExpand}><span className={collapsedClass}></span></a></div>);
        }else{
            return (<div style={{width: "21px"}}></div>);
        }
    }

    render() {
        const {
            connectDropTarget, 
            connectDragPreview, 
            connectDragSource, 
            isDragging,
            item: {id, outline_title, children, type}, 
            parent, 
            drop, 
            find,
            itemAttributes,
            onDelete,
            onDeleteRevert,
            onEdit,
            itemRename,
            onItemActive,
            activeNode,
        } = this.props

        if(isDragging){
            return null;
        }

        var collapseExpandBtn = this.addExpandCollapseBtn();

        var changed = this.props.item.changed ? nodeStyle.changed : null;
        var active = this.props.active ? nodeStyle.active : null;

        var hoverClass = '';
        if(this.state.isHovering){
            hoverClass += nodeStyle.hover;
        }

        //if deleted than toggle opacity class and buttons
        var deleted = '';
        if(this.state.deleted){
            deleted = nodeStyle.deleted;
            var revertClass = 'glyphicon glyphicon-repeat';
            var buttons = this._revertButton(this.props.item);

        }else if(this.state.editing){
            var buttons = this._confirmEditButton();
        }
        else{
            var buttons = this._deleteButton(this.props.item);
        }

        let itemStyle = {};
        if(!children){
            var children_data = [];
            var nodeStyling = nodeStyle.item;
        }
        else{
            var children_data = children;
            var nodeStyling = nodeStyle.item;
            if(this.state.collapsed){
                itemStyle.marginBottom = "10px";
            }
        }

        var nodeClass = 'list-group-item ' + nodeStyling + ' '+ changed +' '+deleted +' '+active;

        var nodeType = this.props.item.type.toUpperCase().replace(/ /g,"_");

        //get icons and styles from node attributes
        var iconClass = '';
        if(itemAttributes[nodeType].icon){
            iconClass += itemAttributes[nodeType].icon;
        }
        var style = {};
        if(itemAttributes[nodeType].color){
            style.backgroundColor = itemAttributes[nodeType].color
        }

           return (
                <div className={nodeStyle.itemContainer} style={itemStyle}>
                    {collapseExpandBtn}
                    { connectDropTarget(connectDragPreview(<li 
                        data-type={this.props.item.type} 
                        key={this.props.item.id} 
                        data-nodeid={this.props.item.id}
                        className={nodeStyle.outerItem}
                    >
                    <div>  
                            {connectDragSource(
                                <div 
                                    className={nodeClass}
                                    onMouseOver={this.handleMouseOver} 
                                    onMouseOut={this.handleMouseOut}
                                >
                                <div style={{display: "table-row"}}>
                                <div style={{backgroundColor: this.props.itemAttributes[nodeType].color}}>
                                    <div style={{fontSize: "10px", lineHeight: "5px"}}>&nbsp;{this.props.index}</div>
                                    <div>
                                        <i className={iconClass}></i>
                                    </div>
                                </div>
                                <div className="title" onClick={this.getClickHandler(this.onEditClick.bind(null, this.props.item), this.enableRename)}>
                                    {this.state.nodeTitle}
                                </div>
                                <div className={hoverClass}>
                                    <div>{buttons}</div>
                                </div>
                                </div>
                            </div>
                            )}
                        </div>
                        <Menu
                            parent={id}
                            children={children_data}
                            drop={drop}
                            find={find}
                            itemAttributes={itemAttributes}
                            itemDelete={onDelete}
                            itemRevert={onDeleteRevert}
                            itemEdit={onEdit}
                            itemRename={itemRename}
                            onItemActive={onItemActive}
                            activeNode={activeNode}
                            collapsed={this.state.collapsed}
                            ref="menu"
                        />
                    </li> ))}
                </div> 
            );
    }
}
```

**Comment by gaearon** [comment] 2016-02-14 00:03
This is a lot of code and is very specific to your use case. I can’t run this code easily. There is no sequence of steps with the screenshots for each step to reproduce the problem either. Helping you would involve taking a day of my time just to get this project to build from the parts you posted, which is still unlikely because this code is just components. If you took time to *extract* the relevant code and simplify the problem so components only contain the code relevant *to the problem* you posted, it could work better.

I am going to close this because unfortunately I don’t understand what you are trying to do, and the code is not very helpful because I can’t run it, and because it is so long so I’m not sure which parts are relevant. If you can reduce your problem to something isolated and specific, and host it somewhere like JSBin so it is easy to run and debug, I am happy to reopen and try to help.

Thank you for your time!

**Closed by gaearon** 2016-02-14 00:03 UTC

**Comment by mishoboss** [comment] 2016-10-10 21:18
Hello, @3Cbwaltz ! Any chance to publish the whole code? Seems you did something I try to do too.
