### ISSUE TITLE
Performance problems with DropTargets > 1000

### ISSUE THREAD

**Issue by ConneXNL** [gaearon/react-dnd#421] opened 2016-03-29 19:50 UTC
I am currently developing in app which is somewhat like a spreadsheet. You are able to move a cell around in the grid. There are also multiple sheets. I DO NOT need support to drag a cell to a different sheet. However, as I add more sheets and thus increase the amount of cell components aka DropTargets, the app slows down significantly.

With ~300 it's still running smooth but anywhere above a 1000 DropTargets slows down significantly as the DropTarget:collect function seems to be called on all DropTargets every X ms.

I added a DragContext on each sheet component in the hope that DropTarget:collect would only be called on the current context's children but that wasn't the case. I hoped to use the "types" with a callback function but that didn't optimize the performance.

Am I missing something in the current library that could help or is it expected that it becomes super slow with >1000 dropTargets.

Are there any work arounds? 
Maybe a temporary way to disable a group of DropTargets?

**Comment by gaearon** [comment] 2016-04-02 20:57
Have you considered using something like https://bvaughn.github.io/react-virtualized/? While technically you can stretch React DnD performance to ~3000 items, there’s no way for it to not lag after a certain point without changing the API (and making it less useful). If you have thousands of rows, I think you should be using virtualized lists anyway.

Luckily, React DnD should work fine with virtualized lists because you can implement a custom `isDragging` on the drag source, and then it doesn’t matter that the component gets reused. So I’m closing it as wontfix but I hope what I suggested helps. In any case, check out `Sortable/Stress Test` example as it shows a few perf techniques that can help achieve acceptable-ish performance with <5000 items. Of course it really depends in how complex your DOM is, too.

**Closed by gaearon** 2016-04-02 20:57 UTC

**Comment by scarletsky** [comment] 2016-07-10 06:27
Hello, @gaearon .
I have a similar issue problem and it can reproduce in https://github.com/scarletsky/react-redux-dnd-demo

This is a demo and in my production case, it is more complex. Here is a snapshoot:

![untitled](https://cloud.githubusercontent.com/assets/2386165/16711968/121b44ac-46a9-11e6-9ddc-a3e99c64fa83.gif)

I need to recalculate the hoverArea when dragging `composite toys`, while `single toy` needn't to do this. As the result, dragging `single toy` is really smooth, but dragging `composite toys` is really lagging.

**Comment by gaearon** [comment] 2016-07-10 09:23
I'm not actively working on this library. I described how to optimize this in the above comment. The standard React optimizations (shouldComponentUpdate) apply here as well. Unfortunately I can't help you beyond that: either try optimizing your components further or switch to a virtualized table.

**Comment by scarletsky** [comment] 2016-07-11 03:35
@gaearon 
Thanks for your quick reply. I've try the `shouldComponentUpdate` way, it seems OK if I move the toys slowly. But when I move the toys quickly, every cells will trigger `shouldComponentUpdate` method, and it become lagging.
I notice that when I dragging a single toy, it is unnecessary to dispatch a action to calculate the hoverArea. But when dragging the composite toys, it needs to dispatch a action to calculate the hoverArea. If the dragging move quickly, tons of actions dispatch, and tons of  `shouldComponentUpdate` trigger.

Here is the hover implementation
```js
  hover(props, monitor) {
    const item = monitor.getItem();
    if (item.type !== ToyTypes.COMPOSITION) return;

    const { dispatch, cell, section } = props;

    if (cell.id !== props.hoverId) {
      dispatch(updateSelectionHoverArea({
        cell,
        section,
        grid: item.props.grid
      }));
    }
  },
```

Maybe my question is related to frequently actions of redux?

**Comment by gaearon** [comment] 2016-07-11 11:01
Sorry, I can’t really help here. Redux is super tiny so you can treat it like regular JavaScript. Start profiling in Chrome, do what you do, stop it, then look at the flamechart and see where the time is being spent. Think about how to do less work there.

**Comment by scarletsky** [comment] 2016-07-12 01:01
@gaearon Ok, thanks!

**Comment by SourceCode** [comment] 2017-08-13 10:28
While Dan is right about using virtualized, what I have found is that a great method of reducing the total calls and improving performance is to debounce certain methods so that they only fire so often.  Out of the box certain events will just fire as fast as they can, such as canDrop, isOver, and the component re-rendering.  My quick and simple solution was to debounce these calls so they scale back the total calls made.  This reduction allows much larger grids to be used out of the box with the react-dnd.

**Comment by acusti** [comment] 2017-10-23 19:06
@SourceCode We’re looking into this, too, for a use case where it is very challenging to use a virtualized list or table. When you say you debounced certain methods, do you mean you forked react-dnd and internally debounced how often it triggers canDrop, isOver, and the rest? Also, did you wind up debouncing or throttling those events?

**Comment by SourceCode** [comment] 2017-10-26 19:49
@acusti I just debounced the events within the library in my own branch.  So the calls are using debounce at 100 - 250ms, rather than firing as fast as possible.  What I did find was that after exporting the build of my app the performance increased (not sure why honestly).  I am using create-react-app for the dev and build process.  My app has roughly 70 rows and 1-100 columns that are holding cards that also have events/images/etc.  The performance has actually been fine after the debouncing of these calls as well as exporting the build of the app.  Hope that helps!

**Comment by acusti** [comment] 2017-11-02 14:05
@SourceCode That’s very helpful, thanks so much for replying!

**Comment by RishiGiant** [comment] 2017-11-29 11:23
@SourceCode we are using React DND and running into a similar situation for large lists that cannot be virtualized. Where did you end up debouncing the events in the source?

**Comment by brenthosie** [comment] 2017-12-14 22:20
I created a very minimal example using `create-react-app` to see if it was my code that was a problem or if it was `react-dnd`.

Unsurprisingly, when running locally with `create-react-app` the drag detection was very slow in updating the hovered elements of my drop targets.

What was surprising is that when I deployed my example to `gh-pages`, the optimized production build seems to have taken care of the sluggishness that I see in my development build.

https://brenthosie.github.io/react-dnd-example/

I'm not an expert in what changes between the prod builds and the development build, but it's surprising to me that the way that I deploy my code is affecting the performance of `react-dnd`.

**Comment by aaronchua13** [comment] 2020-03-16 01:39
> @acusti I just debounced the events within the library in my own branch. So the calls are using debounce at 100 - 250ms, rather than firing as fast as possible. What I did find was that after exporting the build of my app the performance increased (not sure why honestly). I am using create-react-app for the dev and build process. My app has roughly 70 rows and 1-100 columns that are holding cards that also have events/images/etc. The performance has actually been fine after the debouncing of these calls as well as exporting the build of the app. Hope that helps!

can you show us how you did?

**Comment by johnloven** [comment] 2020-04-19 20:17
@acusti You can debounce a collect function using hooks like this.

Here I'm using it to debounce the collect function of the 'useDragLayer' hook since that otherwise is called continuously while dragging, which is very expensive. However you can use this technique for other hooks as well.

---

Custom hook helping with debounce timings:
```jsx
// Calling 'wait(millis)' will set 'done' to false
// and after 'millis' ms set 'done' to true. 
function useWait() {
    const [ done, setDone ] = useState(true);
    const timeout = useRef();
    const wait = useCallback(millis => {
        clearTimeout(timeout.current);
        setDone(false);
        timeout.current = setTimeout(() => setDone(true), millis);
    }, []);
    return [ wait, done ];
}
```
 In your component:
```jsx
const [ wait, done ] = useWait();

const doneRef = useRef(done);
useEffect(() => { doneRef.current = done });
const collectedPropsRef = useRef();

collectedPropsRef.current = useDragLayer(monitor => {
    // Debounce if 'done' is false.
    // Since 'useDragLayer' doesn't honor it's dependencies
    // you need to use a ref to 'done' for it to catch a change in the value.
    if (!doneRef.current) {
        return collectedRef.current;
    }

    // This will keep 'doneRef.current' false and debounce
    // 'expensiveCollectFunction(monitor)' for 100 ms
    wait(100);

    return expensiveCollectFunction(monitor);
});

// Thanks to debouncing, 'collectedProps' will change at a maximum rate of once every 100 ms
const collectedProps = collectedPropsRef.current;
```
