### ISSUE TITLE
Chessboard example has problems in Safari

### ISSUE THREAD

**Issue by haihappen** [gaearon/react-dnd#155] opened 2015-05-19 08:08 UTC
![](https://s3.amazonaws.com/f.cl.ly/items/2s040Y0A0o0H1C3O2O1s/Screen%20Recording%202015-05-19%20at%2010.05%20am.gif)

**Comment by gaearon** [comment] 2015-05-19 12:06
I can't reproduce this. Can you post your exact Safari version, OS X version, screen resolution, and whether your screen is Retina? Thanks!

**Comment by haihappen** [comment] 2015-05-19 12:27
My system should be up-to-date (on May 19th 2015):

Safari 8.0.6
OS X 10.10.3
Screen Resolution 1440 x 900 on a Retina display

**Comment by gaearon** [comment] 2015-05-19 12:34
Anything unusual in your configuration? Like an external monitor.
I'm updating Safari from 8.0.5 but I doubt that's the issue..

Any problems in other browsers?

**Comment by gaearon** [comment] 2015-05-19 12:36
Not having this problem on 8.0.6 either. What's your hardware?

**Comment by haihappen** [comment] 2015-05-19 12:45
Hm… I tested it now on my external display too, which is the current Thunderbolt Display from Apple. It doesn't work either, whether I’m using both displays or just one of them.

Chrome and Firefox work fine.

**Comment by haihappen** [comment] 2015-05-19 12:47
Ok, found the problem: https://chrismatic.io/ublock/ <https://chrismatic.io/ublock/> This is my current adblocker and disabling it fixes the problems. However I’m using it in Chrome as well, which is working fine.

**Comment by gaearon** [comment] 2015-05-19 15:16
Thanks. Indeed, ublock was overriding the `Image` constructor so the `instanceof` check failed. I replaced it with some duck typing, and it should be more correct now. This will get into the next minor release.

**Comment by gaearon** [comment] 2015-05-26 23:05
This should be fixed in 1.1.
Please verify.

**Comment by haihappen** [comment] 2015-05-27 05:33
Will look into it when I'm back home. :)

**Comment by haihappen** [comment] 2015-05-27 08:19
Is the new version already used for the Chessboard example?

I'm now getting following errors - with disabled extensions!

![screen shot 2015-05-27 at 10 17 47](https://cloud.githubusercontent.com/assets/14321/7831742/dfcd5ca2-0459-11e5-819e-c25d96bea427.png)
![screen shot 2015-05-27 at 10 17 55](https://cloud.githubusercontent.com/assets/14321/7831745/e311b34a-0459-11e5-8114-6fa77b6492bf.png)

**Comment by hakanderyal** [comment] 2015-05-27 08:30
I'm getting the same error.

- Custom image is not shown while dragging.
- When I drop to an invalid location, it still stays in 'dragging' state.
- If I drop to a valid location, it works fine.

Safari Version 8.0.2 (10600.2.5) - no extensions.

**Comment by hakanderyal** [comment] 2015-05-27 08:33
Just checked the other examples in safari, invalid drops cause it to stuck in `dragging` state.

And starting dragging always produces the same error, on the same line `HTML5.js:157`

```
[Error] TypeError: null is not an object (evaluating 'Array.prototype.slice.call(n.types)')
	slice (main-e36e66a10c13c4e9d8ac.js, line 1)
	l (main-e36e66a10c13c4e9d8ac.js, line 1)
	handleTopDragStart (main-e36e66a10c13c4e9d8ac.js, line 1)
	(anonymous function) ([native code], line 0)`
```

**Closed** 2015-05-27 10:18 UTC

**Comment by gaearon** [comment] 2015-05-27 10:19
Thanks! Should be fixed now. Browsers :scream:. I'm starting to think HTML5 backend should be moved to a separate repo so I can bump its versions without bumping React DnD.
