### ISSUE TITLE
demo not working on phone

### ISSUE THREAD

**Issue by flyon** [gaearon/react-dnd#31] opened 2015-01-08 10:18 UTC
If I load the demo on my phone I can't move anything.
Are touch events supported? If not do you think it would be possible to use this library with some existing scripts that map touch events to mouse events?

**Comment by gaearon** [comment] 2015-01-08 12:12
This is planned but I'm quite busy at the moment so if somebody wants to implement this, I can give guidance on best way to do it.

Duplicate of #16.

**Closed by gaearon** 2015-01-08 12:12 UTC
