### ISSUE TITLE
Firefox is navigating to dragged image URL on drop

### ISSUE THREAD

**Issue by Enet4** [gaearon/react-dnd#221] opened 2015-07-02 17:14 UTC
For some reason, FF's default behavior was not prevented in my project. I have a drag source `ImageItem` containing an image, and dropping it over my drop target will not only trigger my logic in the web application, but also issue a navigation to the image's URL.

> In Firefox 3.5+, the default behavior for a drop event is to navigate to the URL that was dropped on the drop target. That means dropping an image onto the drop target will result in the page navigating to the image file ([ref](http://www.developerfusion.com/article/144828/the-html5-drag-and-drop-api/))

I may provide more information on request. The examples appear to work fine. I wish I had an SSCCE of the problem... This could also be related to #219.

**Comment by gaearon** [comment] 2015-07-08 11:07
This indeed seems like a duplicate of #219.
I don't currently have time to work on this but I'm happy to provide guidance if you'd like to fix it.

**Comment by gaearon** [comment] 2015-09-17 21:20
Fixed in https://github.com/gaearon/react-dnd/commit/2299ecea6f292a5814c7efd6ae3460066b6b8707.

**Closed by gaearon** 2015-09-17 21:20 UTC
Labels: bug

**Comment by gaearon** [comment] 2015-09-17 21:27
The fix for this issue was released in `react-dnd@1.1.8`.
Please verify that it works.

**Comment by thomasvm** [comment] 2015-11-10 15:51
I had this very issue, and I can confirm that this is fixed after upgrading to react-dnd@1.1.8
