### ISSUE TITLE
Demo does not work on mobile

### ISSUE THREAD

**Issue by winkler1** [gaearon/react-dnd#33] opened 2015-01-19 18:52 UTC
http://gaearon.github.io/react-dnd/#/dustbin-interesting

... need to initialize React for touch?

**Comment by gaearon** [comment] 2015-01-19 19:01
It doesn't support touch (at least not yet).
The reason is we're basing on HTML5 Drag and Drop API and no touch browsers implement it.

This is not a *hard* limitation of this library. I do plan an optional touch backend in the future (see #16 and https://github.com/gaearon/react-dnd/issues/16#issuecomment-63743944 for groundlaying work), but since it's not a priority for my main job at the moment, I'm not actively developing that.

If you like the API and feel like doing some work to make it happen, ping me and I can help you get up to speed and give some hints as to how this can be implemented.

**Comment by gaearon** [comment] 2015-01-19 19:02
Closing this as a duplicate of #16. Feel free to chime in there!

**Closed by gaearon** 2015-01-19 19:02 UTC

**Comment by winkler1** [comment] 2015-01-19 19:14
Thanks. Will keep in mind if I work on a dnd project!
