### ISSUE TITLE
Drag offset is incorrect in Firefox

### ISSUE THREAD

**Issue by moroshko** [gaearon/react-dnd#191] opened 2015-06-13 14:03 UTC
Steps to reproduce:

    1. git clone git@github.com:moroshko/react-chessboard.git
    2. cd react-chessboard
    3. git checkout 87d1f56d108da439540656cf02ce928ec959dcd0
    4. npm install
    5. npm start
    6. Open http://localhost:3000/examples/dist/index.html in Firefox
    7. Click on the "+" of the King, and start dragging
    You'll see that the cursor is no longer on the "+"

(In Chrome, the cursor stays on the "+", which is the expected behaviour)

Firefox 38.0.5
OS X Yosemite 10.10.3

Here are 2 videos that demonstrate the issue:
* [The buggy behaviour - Firefox](https://dl.dropboxusercontent.com/u/1893981/Firefox.mov)
* [The expected behaviour - Chrome](https://dl.dropboxusercontent.com/u/1893981/Chrome.mov)

**Comment by gaearon** [comment] 2015-06-13 16:48
Retina?

**Comment by moroshko** [comment] 2015-06-14 01:52
@gaearon Nope

**Comment by gaearon** [comment] 2015-06-14 12:05
Unfortunately I don't have time to fix this in the following three weeks (I'm preparing for a conference talk). The problem is [likely to be in this function](https://github.com/gaearon/react-dnd/blob/d97c1b6ea21df39cbc1ebf73d3359a6a25fe371e/src/utils/OffsetHelpers.js#L260). It's trying to get around browser bugs with Retina/non-Retina screens, but it's possible that non-Retina Firefox behavior is wrong. I'd gladly accept a PR fixing it.

**Comment by gaearon** [comment] 2015-09-17 20:49
I'm closing because I'm unable to reproduce and I don't have a Retina-less screen. As I wrote above, there is a specific place in code where these calculations happen, so it shouldn't be hard to fix and send a PR once you reproduce the problem reliably.

**Closed by gaearon** 2015-09-17 20:49 UTC
Labels: bug
