### ISSUE TITLE
Error in bindConnectorMethod

### ISSUE THREAD

**Issue by brigand** [gaearon/react-dnd#261] opened 2015-08-09 02:54 UTC
I'm getting this error in shallowEqual from [bindConnectorMethod][1] where it expects `currentOptions` to be an object, but it's `undefined`.

It doesn't appear to impair functionality (dragging is a bit glitchy but maybe unrelated), and only happens when inserting a new item.

> (Object.keys) Uncaught TypeError: Cannot convert undefined or null to object

![image](https://cloud.githubusercontent.com/assets/936069/9153364/3c00681c-3e06-11e5-920b-c05dbb5ae2bb.png)

Any tips on how to narrow it down to a repro case?

I'd like to add a better error message once I figure it out, assuming it's not an actual bug.

[Full stack trace.](https://gist.github.com/brigand/228c00c35148b2f7b2bb)

Edit:
Caused by this diff: https://gist.github.com/brigand/facd66d909216e6df714  
Backend: HTML5Backend

[1]: https://github.com/gaearon/react-dnd/blob/c8792616ac9c191001c2a94bfe06752c7f95f32a/src/bindConnectorMethod.js#L25

**Comment by marudor** [comment] 2015-08-17 06:38
I've got the same Issue in my Project. I worked around it by using the shallowEqual Library instead of the shallowEqual in reactDnD.
Main Problem seems to be the `a === b` check in the shallowEqual.
a is undefined while b is null.

@gaearon any reason to shallowEqual instead of shallowEqualScalar (or the shallowEqual npm module)
Just changing that worked for me. See my Fork (https://github.com/marudor/react-dnd)

**Comment by gaearon** [comment] 2015-08-18 16:36
I'd appreciate a runnable example reproducing this.

**Comment by marudor** [comment] 2015-09-15 06:37
For me your latest change (1.1.6) fixed this.
I assume due to your Change in dnd-core.

**Comment by gaearon** [comment] 2015-09-15 13:34
Interesting. I'll close for now; please reopen if you have a reproducible example.

**Comment by marudor** [comment] 2015-10-20 07:04
Okay, this is still an Issue.
Sadly I still have no real small example to show you. Only able to reproduce it in our company app which I can't share.
It is fixed by my scoped release (I just change your shallowEqual implementation with the shallowequal npm package)

Any reason you're using your own instead of the npm package?
I guess using your shallowEqualScalar method everywhere would also work.

**Comment by gaearon** [comment] 2015-10-20 11:56
`shallowEqualScalar` implements completely different logic from `shallowEqual`.
It returns `false` if either value is object, which is the opposite of the effect I want here.

**Comment by gaearon** [comment] 2015-10-20 12:13
Should be fixed in 2.0.1.

**Closed** 2015-10-20 12:13 UTC
Labels: bug

**Comment by gaearon** [comment] 2015-10-20 12:27
Actually you should use 2.0.2, it includes a more correct fix.

**Comment by marudor** [comment] 2015-10-21 06:31
Thanks, looks fixed to me. (Although I just quickly checked, I will tell you if I encounter this again)
