### ISSUE TITLE
Got the Invariant Violation: Could not find the drag and drop manager in the context of Card

### ISSUE THREAD

**Issue by roine** [gaearon/react-dnd#171] opened 2015-05-28 11:31 UTC
I receive this error:
   > Invariant Violation: Could not find the drag and drop manager in the context of Card

I've set the DragDropContext to my outermost Component. I'm not sure whether it's relevant but my `Card` Component is deeply nested.

The DOM looks like:

```
<DragDropContext(Container)>
    <Media>
        <Pin>
            <List>
                <DragSource(Card)></DragSource(Card)>
            </List>
        </Pin>
    </Media>
</DragDropContext(Container)>
```
I thoroughly followed the examples and can see only one difference and it's in the deep nesting of the DragSourced Component. Am I missing anything?

Edit: Another reason I can think of is that I'm using reflux.

Full Error message
>Warning: Failed Context Types: Required context `dragDropManager` was not specified in `DragSource(Card)`.
index.js:4692 Uncaught Error: Invariant Violation: Could not find the drag and drop manager in the context of Card. Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://gaearon.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context

**Comment by vkbansal** [comment] 2015-05-28 17:26
May be it is due to the way you are using `<DragDropContext(Container)></DragDropContext(Container)>`

Try this :
```
var DDContainer = DragDropContext(Container);
var DSCard = DragSource(Card);
<DDContainer>
    <Media>
        <Pin>
            <List>
                <DSCard></DSCard>
            </List>
        </Pin>
    </Media>
</DDContainer>
```

**Comment by roine** [comment] 2015-05-29 10:20
Hi Vkbansal,

I tried your approach but the error message keeps popping in. I'll investigate further but I cant see what I am doing wrong. For info I'm using browserify, es6 and reflux, could those libs be the issue?

**Comment by vkbansal** [comment] 2015-05-29 11:24
Have you looked the documentation?
http://gaearon.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context

> There are several ways this error might have happened:
1. You wrapped some component with a DragSource, DropTarget, or DragLayer, but forgot to wrap your top-level component with the DragDropContext.
2. You have wrapped the top-level component with the DragDropContext but exported an unwrapped version by mistake.
3. You are using a component in an isolated environment like a unit test. See the second point for instructions to stub it.
4. The context is lost for some other reason. Please file an issue if you can reproduce it on a small project.

You may be getting the error due to the first point. It's a common mistake that I make.

**Comment by roine** [comment] 2015-05-29 11:37
I did wrap my top-level component with DragDropContext.

**Comment by gaearon** [comment] 2015-05-29 11:51
Any chance you have duplicate Reacts on the page?

**Comment by roine** [comment] 2015-05-29 12:01
I dont think so, I'm requiring React with browserify on all the pages that require React, but I dont think browserify is creating a duplicate.

**Comment by gaearon** [comment] 2015-05-29 12:13
Yeah that's the problem. `DragDropContext` needs to be placed on *the owner* of the hierarchy, not just the parent. That's why I call it top-level component in the docs. In other words, if it receives `children`, they won't get the context.

This is [going to be fixed in React 0.14](https://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#solution-make-context-parent-based-instead-of-owner-based), but for now, you'll need to slap `DragDropContext` onto whoever creates those `children`.

**Closed by gaearon** 2015-05-29 12:13 UTC

**Comment by roine** [comment] 2015-05-29 14:15
It seems to work, thank you.

Awesome project btw.

**Comment by OlehHappy** [comment] 2016-02-15 15:47
thanks it was helpful, because I used 0.14.alpha version of React. Updated to 0.14.7 and problem with 
```Uncaught (in promise) Error: Invariant Violation: DragDropContext```

solved
