### ISSUE TITLE
Ctrl-A from an <input> inside a DragSource component broken (Chrome)

### ISSUE THREAD

**Issue by warrd** [gaearon/react-dnd#266] opened 2015-08-19 09:23 UTC
Does not select the text (at least not for me).

Tested in firefox and works.

**Comment by gaearon** [comment] 2015-09-17 20:41
Fixed by https://github.com/gaearon/react-dnd/commit/0a36033693868a7985ea2348105da4fb2cef8a00.
Duplicate of #178.

**Closed by gaearon** 2015-09-17 20:41 UTC
Labels: bug

**Comment by gaearon** [comment] 2015-09-17 21:29
The fix for this issue was released in `react-dnd@1.1.8`.
Please verify that it works.
