### ISSUE TITLE
Could not find the drag and drop manager in the context  with EventEmitter

### ISSUE THREAD

**Issue by childku** [gaearon/react-dnd#185] opened 2015-06-08 08:26 UTC
I have wrapped the DragApp which is the top component with the DragDropContext
 ```
  ...
  export default DragDropContext(HTML5Backend)(DragApp);
 ```
 In the 'drop' method in DragTarget I trigger an event with EventEmitter, then in the listening-end I render React object, I found this error: `Uncaught Error Invariant Violation: Could not find the drag and drop manager in the context of Text. Make sure to wrap the top-level component of your app with DragDropContext`

this is the emitter.js which is extended from EventEmitter
```
import {EventEmitter} from 'events';

class Emitter extends EventEmitter {

  onDrop(options){
    this.emit("onDrop", options);
  }
}

export default new Emitter();
```

this is the container.jsx which trigger the 'onDrop' event with EventEmitter.
```
const containerTarget = {
  drop(props, monitor, component) {
    emitter.onDrop({type: monitor.getItemType(), index: props.index});
    return { name: 'Container' };
  }
};

function collect(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
    canDrop: monitor.canDrop(),
    itemType: monitor.getItemType()
  };
}

class Container extends Component {
  ...
}

export default DropTarget([ItemTypes.TEXT_CLASS, ItemTypes.TEXT], containerTarget, collect)(Container);
```

this is the form.jsx which handles the ‘onDrop’ event, in the 'bindEventEmitterListener' method the error was thrown.
```
class Form extends Component {
  bindEventEmitterListener(): void {
    emitter.on('onDrop', (options) => {
      this.renderElement();
    });
  }
  componentWillMount(): void {
    this.bindEventEmitterListener.apply(this);
  }
  renderElement() {
    return (
      <Text id={uuid()} />
    );
  }
}

export default Form;
```

i think that maybe the emitter does not have the DragDropContext environment, but i Don't know how to create an Object with DragDropContext

**Comment by gaearon** [comment] 2015-06-08 15:41
This is not related to `EventEmitter`. Context is a React (undocumented) feature so it only concerns React components.

What does `DragApp` look like? If it accepts `children` as a prop and doesn't render `Form` itself, that's where the problem comes from.

Also, I'm a bit confused about your example. What is the relation between `Container` (which seems to be the drop target) and `Text` (which appears in the error message)?

**Comment by childku** [comment] 2015-06-09 03:27
this is the drag-app.jsx

```
import React, { Component } from 'react';
import {Table}              from 'react-bootstrap';
import { DragDropContext }  from 'react-dnd';
import HTML5Backend         from 'react-dnd/modules/backends/HTML5';
import Form                 from './form';
import TextClass            from './text-class';
import PropertyPanel        from './property-panel';

class App extends Component{
  render() {
    return (
      <Table >
        <tbody>
          <tr >
            <td>
              <Form />
            </td>
            <td>
              <TextClass name='input'/>
            </td>
          </tr>
          <tr>
            <td colSpan='2'>
              <PropertyPanel />
            </td>
          </tr>
        </tbody>
      </Table>
    );
  }
}

export default DragDropContext(HTML5Backend)(App);
```

`Container` is the drop target. `Text` is a React object which is wrapped with DragSource,
 `Form` will create a `Text` instance when I drop `TextClass`(a drag source) into `Container`.

this is the full form.jsx
```
class Form extends Component {
  constructor(props: any): void {
    super(props);
    this.state = {elements:[]};
  }

  bindEventEmitterListener(): void {
    emitter.on('onDrop', (options) => {
      let elements = this.state.elements;
      let element = this.renderElement();

      elements.push(element);
      this.setState({elements: elements});    
    });
  }

  componentWillMount(): void {
    this.bindEventEmitterListener.apply(this);
  }
  renderElement() {
    return (
      <Text id={uuid()} />
    );
  }
  render() {

    return (
      <form className='form-horizontal' >
        {this.state.elements}
        <Container  />
      </form>
    );
  }
}

export default Form;
```



this is the text-class.jsx, which is a drag source.
```
const textClassSource = {
  beginDrag(props) {
    return {
      name: props.name
    };
  },

  endDrag(props, monitor) {
    const item = monitor.getItem();
    const dropResult = monitor.getDropResult();

    if (dropResult) {
      console.log(`You dropped ${item.name} into ${dropResult.name}!`);
    }
  }
};

function collect(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  };
}

class TextClass extends Component {
  render() {
    const { isDragging, connectDragSource } = this.props;
    const { name } = this.props;
    const opacity = isDragging ? 0.4 : 1;
    const style = {
      border: '1px dashed gray',
      backgroundColor: 'white',
      padding: '0.5rem 1rem',
      marginRight: '1.5rem',
      marginBottom: '1.5rem',
      cursor: 'move',
      float: 'left',
      opacity: opacity
    };
    return (
      connectDragSource(
        <div style={style} >
          {name}
        </div>
      )
    );
  }
}

export default DragSource(ItemTypes.TEXT_CLASS, textClassSource, collect)(TextClass);
```

this is the text.jsx, `Form` will create a `Text` instance with the `renderElement` method when I drop `TextClass` into `Container`.

```
const textSource = {
  beginDrag(props) {
    return {
      id: props.id,
      name: props.name
    };
  },

  endDrag(props, monitor) {
    const item = monitor.getItem();
    const dropResult = monitor.getDropResult();

    if (dropResult) {
      console.log(`You dropped ${item.name} into ${dropResult.name}!`);
    }
  }
};

function collect(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  };
}

class Text extends Component {
  constructor(props: any): void {
    super(props);
    this.state = {id: uuid()};
  }

  render() {
    const {connectDragSource } = this.props;

    return (
      connectDragSource(
        <div className='form-group'>
          <label className='col-sm-2 control-label' >Text</label>
          <div className='controls'>
            <input type='text' placeholder='text' className='form-control' />
          </div>
        </div>
      )
    );
  }
}

export default DragSource(ItemTypes.TEXT, textSource, collect)(Text);
```

**Comment by gaearon** [comment] 2015-06-09 10:57
The problem is you're creating `<Text>` element outside `render`. In React 0.13, it causes it to not receive the context. In React 0.14 this will be fixed, but in the meantime, consider operating *on data* in your drag and drop handlers, and then using `render` to react to changes in that data.

**Closed by gaearon** 2015-06-09 10:57 UTC

**Comment by childku** [comment] 2015-06-09 12:52
Thanks a lot!
