### ISSUE TITLE
Ask about the dataTransfer dragpreview

### ISSUE THREAD

**Issue by cuongcua90** [gaearon/react-dnd#30] opened 2015-01-05 11:13 UTC
I am writing a custom drag and drop sortable. I got the problem which example of sortable solved. But I want to self write my own lib with small function.

My problem is how to style the drag source and drop target with different style. (In this case, the drop target maybe blank and drag source is our component). I read code and see the lib use dataTransfer and setDragImage is dragpreview. But I don't know how to get the dragpreview.

Any body suggest me a simple solution?

**Comment by gaearon** [comment] 2015-01-05 14:37
I'm not 100% sure I understand your question.

Do you want to:

1. Use custom drag image instead of default (by default, drag source is screenshotted)

2. Change appearance of drag source and/or drop target while dragging occurs

3. Use custom drag preview and change something in it in the middle of a drag operation

?

Do any of the examples help?

**Comment by cuongcua90** [comment] 2015-01-05 15:22
In my case, when I drag a component or node. The drag over and drag component have same styles. I must use something like this : 
   var node = _.extend({}, this.getDOMNode());
   document.body.appendChild(node);
   e.dataTransfer.setDragImage(node, e.clientX/2, this.getDOMNode().offsetHeight/2);

to show the dragging component. And set the drag over with opacity = 0 like you. But got the problem with react id.

In your code you set dataTransfer for dragPreview. But I do not know how to get it?

**Comment by gaearon** [comment] 2015-01-05 18:04
I still don't understand what you're trying to do. Maybe some screenshots would help?

**Comment by cuongcua90** [comment] 2015-01-06 02:07
I want to use custom drag preview (with custom style). And I want to know how to get dragpreview in your code. I read code and in the function beginDrag() I do not see where the dragpreview in it.

**Comment by gaearon** [comment] 2015-01-06 06:05
Do you want to hide the drag source while item is being dragged? You don't need `dragPreview` for that, just set opacity to 0 (or return null from render) when `this.getDragState(TYPE).isDragging` is `true`.

See this example (tick "Hide source whole dragging" checkbox): http://gaearon.github.io/react-dnd/#/drag-around-naive

Source: https://github.com/gaearon/react-dnd/blob/master/examples/_drag-around-naive/Box.js#L42

Does this help?

**Comment by cuongcua90** [comment] 2015-01-06 06:27
Thank you @gaearon. I'm writing sortable list. And I want when I drag the item we can change the style of dragging item (and also hide the drag source). For example when we drag the box in the example. We may change the border color to red.

**Comment by gaearon** [comment] 2015-01-06 17:57
@cuongcua90 

I see now. Sadly it's not easily possible due to how browser D&D API works but it's something I was experimenting with [in this branch](https://github.com/gaearon/react-dnd/commits/experiments). [See this example (not in master)](https://github.com/gaearon/react-dnd/tree/experiments/examples/_drag-around-experimental).

I haven't had time to complete this, but I may be able to do so during next few weeks if it's a priority to you. Let me know if this matches what you're looking for.

Seems like a duplicate of #17.

**Comment by cuongcua90** [comment] 2015-01-07 02:01
Thank @gaearon  so much. I will see your experiment and learn from it. It is exactly what I am looking for.

**Comment by gaearon** [comment] 2015-01-19 10:44
Closing this for now, as this pretty much repeats #17.
Let me know if you come up with something!

**Closed by gaearon** 2015-01-19 10:44 UTC

**Comment by gaearon** [comment] 2015-02-17 19:53
This is available in 0.8.0 using `DragLayerMixin`.

[Live demo](http://gaearon.github.io/react-dnd/#/drag-around-custom)
[Source code](https://github.com/gaearon/react-dnd/tree/master/examples/_drag-around-custom)

**Comment by cuongcua90** [comment] 2015-02-27 10:17
thanks @gaearon. It works well. Just problem with performance when the drag component is complicated.

**Comment by gaearon** [comment] 2015-02-27 12:05
>Just problem with performance when the drag component is complicated.

You should use [`PureRenderMixin`](http://facebook.github.io/react/docs/pure-render-mixin.html) (or manually implement [`shouldComponentUpdate`](http://facebook.github.io/react/docs/advanced-performance.html) to avoid reconciling the child component on each position change. It should be fast in this case. Have you tried it?

**Comment by gaearon** [comment] 2015-02-27 12:07
Added this to docs: https://github.com/gaearon/react-dnd/commit/6c95eb1a011965f9aa35680081ba1fe58ee4e643

**Comment by cuongcua90** [comment] 2015-02-27 15:48
Better now, thanks for your support. It's very good

**Comment by gaearon** [comment] 2015-02-27 17:06
:+1:

**Comment by dgrcode** [comment] 2020-01-28 16:48
Just found this thread looking for an example of using the equivalent of [`DataTrasnfer.setDragImage()`][1]. Links in the thread seem to be broken, so I'll put here the relevant updated links.

 * [Documentation with live demo][2]
 * [Live demo][3]
 * [Source code][4]
 * [CodeSandbox version][5]

[1]: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage
[2]: https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer
[3]: https://3qm8v.csb.app/
[4]: https://github.com/react-dnd/react-dnd/tree/gh-pages/examples_decorators_js/02-drag-around/custom-drag-layer
[5]: https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_decorators_js/02-drag-around/custom-drag-layer?from-embed
