### ISSUE TITLE
demos buggy in Firefox

### ISSUE THREAD

**Issue by tomByrer** [gaearon/react-dnd#391] opened 2016-02-25 18:52 UTC
Seems DnD keeps locking up when I interact randomly
* [custom drag](https://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) the top one drags around OK, then I dropped outside box.  Tried to drag the lower box, but it only blinks off & on.  Can't select other object now.  Refeshing page makes both work as expected.
* [nesting sources](https://gaearon.github.io/react-dnd/examples-nesting-drag-sources.html), if the bottom yellow box is checked, none of the other boxes will drag.

**Comment by gaearon** [comment] 2016-02-28 14:09
Please specify:

* the exact browser version
* the OS, and
* whether you have any errors in console

when filing browser-related bugs. It is impossible to guess and makes this conversation longer than it could have been.

For example, if I knew them now, I could have solved the issue today, but since I don’t, I likely will get back to it only in a week or two. And this is frustrating for both of us since you have a broken app, and I feel guilty about it but can’t fix it because I don’t have enough information :cry: .

As you can see it works for me on:

* Firefox 43.0.3 (OS X)
* Firefox 44.0.2 (OS X)
* Firefox 45.0a2 (OS X)
* Firefox 46.0a2 (OS X)


![](https://s3.amazonaws.com/f.cl.ly/items/0L2m2m1a1w3V0F3r2E16/Screen%20Recording%202016-02-28%20at%2014.00.gif?v=9ec9b514)

![](http://f.cl.ly/items/253W3r0y1A3l3O391J2t/Screen%20Recording%202016-02-28%20at%2014.03.gif)

**Comment by kesne** [comment] 2016-08-20 07:08
Seeing as this wasn't reproducible and it's been some time, I'm going to close it out.

**Closed by kesne** 2016-08-20 07:08 UTC
Labels: needs info
