### ISSUE TITLE
Drop Target "Over" event does not fire over the original position of a list item

### ISSUE THREAD

**Issue by andrewdesigner** [gaearon/react-dnd#139] opened 2015-04-17 18:56 UTC
Say,I have a list similar to the sortable list example. I start dragging a list item, and I move it over another list item, however, I have noticed that if I try to move the item that I am dragging back to its original position, neither "Enter", "Over" or "Leave" events work for the drop target. 

Hence, I am only able to move a list item to another position other than its original position.

How do I fix this problem?

**Comment by gaearon** [comment] 2015-04-17 20:33
Can you put up a project that reproduces it?
Also, since the sortable example works, you can try figuring out how your code differs from it.

**Comment by gaearon** [comment] 2015-04-30 19:26
This is the same problem as #138.
It is solved in `v1.0.0-alpha` that is already on NPM.

The final 1.0 will come within a week or so.
Closing.

**Closed by gaearon** 2015-04-30 19:26 UTC

**Comment by gaearon** [comment] 2015-05-19 01:13
This is fixed in the 1.0 that was just released.
