### ISSUE TITLE
Problems with inputs and textareas inside of draggable component

### ISSUE THREAD

**Issue by playpauseandstop** [gaearon/react-dnd#178] opened 2015-06-02 19:49 UTC
I investigate some problems when placing `<input>` and `<textarea>` elements inside of draggable component,

1. `cmd+A` or `Ctrl+A` shortcuts doesn't work for input or textarea (but selecting text with `Shift + Arrows` still works)
2. Attempt to select input or textarea content with touchpad/mouse starts dragging parent element

My draggable component looks like,

![draggable component](https://cloud.githubusercontent.com/assets/21325/7945430/56b87558-0979-11e5-98a9-5f1d68156b72.png)

**Comment by dperetti** [comment] 2015-06-02 20:55
This is caused by the registration on the `selectstart` event, which is apparently only needed for IE compatibility.
If like me you don't need IE compatibility, here was my quick fix that may work for you :
https://github.com/dperetti/react-dnd/commit/06f74ef97e07a9a24c10eab8593f3e2121d4f2ed

**Comment by gaearon** [comment] 2015-06-02 21:56
Thanks for reporting! I'm glad to accept a PR fixing this.

I have two requirements:

* It needs to still have that IE fix.
* Please verify whether `preventDefault()` is needed for the other browsers. I think it prevents the text selection of whatever you tried to drag. If it indeed helps prevent unwanted selection in other browsers, you might want to surround `e.preventDefault()` with some check a la `e.target.tagName !== 'input'` (but a smarter one).

**Comment by ostinru** [comment] 2015-06-10 09:54
Same bug with `<div contentEditable={isEditing} />`.
Also I can't edit it.  `Ctrl+A` and `Shift + Arrows` doesn't work.

**Comment by gaearon** [comment] 2015-06-10 10:41
In the next three weeks I'm going to be busy and I don't have the time for fixing this.
As I said I'm happy to accept a PR with a fix as described in https://github.com/gaearon/react-dnd/issues/178#issuecomment-108110202.

**Comment by stevenhauser** [comment] 2015-07-14 14:45
Was looking into this. If I comment out [the entire `handleSelectStart` function's body](https://github.com/gaearon/react-dnd/blob/master/src/backends/HTML5.js#L565-L571), everything works as expected. Tested this in IE11 and seems to be good there, too. 

@gaearon do you know if there's a specific use case or setup for why the event needs to be handled at all? IE10? Different setup from `textarea`/`input` in a draggable node?

**Comment by gaearon** [comment] 2015-07-14 15:09
The original issue was https://github.com/gaearon/react-dnd/issues/128.
If you can prepare a PR that fixes the problem, but also keeps https://github.com/gaearon/react-dnd/issues/128 working, that would be a huge help.

**Comment by stevenhauser** [comment] 2015-07-14 15:55
Will see if I can look into it. Need to figure out a way to set up a simple test case for IE9.

**Comment by gaearon** [comment] 2015-07-14 19:12
I think `sortable-simple` example failed on IE9 before #128 was fixed.

**Comment by stevenhauser** [comment] 2015-07-14 22:54
@gaearon Yeah that was a good example to use, thanks. A few notes:

1. No other browsers (tested latest Chrome, Safari, FF, and IE 11) seem to care about this. The event doesn't need to be handled whatsoever.
2. IE9 only appears to only *need* the `e.target.dragDrop()` call. Disabling the text selection can be done by creating a handle that covers the entire draggable, wrapping the draggable node in `connectDragPreview` and the handle in `connectDragSource`. While this may sound nasty, AFAIK you're not officially supporting IE9 so is that a reasonable workaround, especially when other problems are likely to arise in that browser? 
3. Point number two is also useful anyway in the case that you have a text input within the draggable. Users can't select text by dragging their mice if `connectDragSource` is applied the the whole node (it ends up dragging the node instead of selecting text), however applying to an invisible handle that is the size of the whole node works very nicely.

Unsure how you want to handle this. Without resorting to UA checking, I don't know that there's a great way to deal with this and it seems to me like it's adding functionality to support an unofficially supported browser that's breaking good browsers which may end up digging a maintenance hole. But that's all my opinion. Regardless, there's a workaround to this issue that also solves other issues.

**Comment by danielbuechele** [comment] 2015-08-20 11:24
Removing the event listener for `selectstart` makes `contentEditable` work in Chrome, but still it's not working in Safari.

**Comment by gaearon** [comment] 2015-09-17 20:41
Fixed by https://github.com/gaearon/react-dnd/commit/0a36033693868a7985ea2348105da4fb2cef8a00.

>Removing the event listener for selectstart makes contentEditable work in Chrome, but still it's not working in Safari.

This is HTML5 drag and drop API issue in Safari. Nothing we can do about it.

**Closed** 2015-09-17 20:40 UTC
Labels: bug

**Comment by gaearon** [comment] 2015-09-17 21:28
The fix for this issue was released in `react-dnd@1.1.8`.
Please verify that it works.

**Comment by playpauseandstop** [comment] 2015-09-23 12:59
Confirmed that Ctrl/Cmd-A works in `<input>` inside a draggable component.

**Comment by sstefoss** [comment] 2016-01-13 16:12
> Attempt to select input or textarea content with touchpad/mouse starts dragging parent element

I see this is not fixed, create a new issue?

**Comment by trevorsmith** [comment] 2016-03-03 23:34
Elements with contentEditable set inside a draggable parent container wouldn't allow me to select text or interact with them in any way. After some digging, I found this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=170139

It appears Chrome has since fixed the issue. Safari's behavior can be fixed in the meantime with CSS:

```
.contenteditable-element {
  user-select: text;
}
```

**Comment by rahul1995** [comment] 2019-07-04 14:26
@trevorsmith This is still not fixing the Firefox's behaviour. Do you know any workaround for Firefox?

**Comment by megawebmaster** [comment] 2020-04-10 10:23
@rahul1995 - I just found out a solution: just store a ref to the draggable DOM node and when user focuses input/textarea set draggable attribute to `false`:

```jsx
const Test = () => {
  const ref = useRef(null);
  const [focused, setFocused] = useState(false);
  const [_, drag] = useDrag({ item: { type: 'test' } });

  useEffect(() => {
    if (ref.current) {
      ref.current.setAttribute('draggable', !focused);
    }
  }, [focused]);

  return drag(
    <textarea ref={ref} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)}></textarea>
  );
};
```

This should do the trick for Firefox :wink:

**Comment by scottydev** [comment] 2022-08-16 02:51
> @rahul1995 - I just found out a solution: just store a ref to the draggable DOM node and when user focuses input/textarea set draggable attribute to `false`:
> 
> ```js
> const Test = () => {
>   const ref = useRef(null);
>   const [focused, setFocused] = useState(false);
>   const [_, drag] = useDrag({ item: { type: 'test' } });
> 
>   useEffect(() => {
>     if (ref.current) {
>       ref.current.setAttribute('draggable', !focused);
>     }
>   }, [focused]);
> 
>   return drag(
>     <textarea ref={ref} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)}></textarea>
>   );
> };
> ```
> 
> This should do the trick for Firefox 😉

Have you considered making a PR? This is a fairly big issue on Strapi when entering data.

https://github.com/strapi/strapi/issues/12432

**Comment by megawebmaster** [comment] 2022-08-16 15:41
To be honest I didn't, because I didn't know where to start - if anyone can point me in the right direction I'm happy to work on the issue :+1:

**Comment by scottydev** [comment] 2022-08-16 17:20
All good, digging in more I saw that your fix has to be applied outside the scope of the react-dnd core. Was trying to apply it [to this ref](https://github.com/strapi/strapi/blob/master/packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js#L172), but the Strapi contrib process was not working correctly on my M1 machine 😅  

There may be a way to use the logic you propose on nested elements and have it bubble up to the draggable ref so we fix it at the React-dnd level for all to make benefit, but we'd have to dig in more to see how that would work.

**Comment by sean-mcclure** [comment] 2022-09-11 20:03
This is a vanilla JS issue, not a React issue. Programmatically focusing the input element when its clicked on fixes the issue.

**Comment by megawebmaster** [comment] 2022-09-19 13:24
@sean-mcclure - so you think a solution like this should work?

```jsx
const Test = () => {
  const [_, drag] = useDrag({ item: { type: 'test' } });

  return drag(
    <textarea onClick={(e) => e.target.focus()}></textarea>
  );
};
```

Why is this a vanilla JS issue and is it reported anywhere in Gecko (Firefox) or Blink (Chromium based browsers)?

**Comment by trainoasis** [comment] 2023-02-02 13:28
A year later almost, but I for some reason found a now soon-to-be-deprecated repo [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) way more intuitive to work with. Have more troubles setting the new repo up for some reason 🤔

**Comment by rbehal** [comment] 2023-12-07 19:29
This is not documented very well, but if you add the class name `nodrag` this works to not allow dragging by the text input field, meaning you can select and highlight text with your cursor. 

No other solutions solved my issue.

```
      <>
        <Input
          disabled={isDisabled}
          value={value}
          onChange={handleChange}
          className={'nodrag'}
          placeholder={placeholder}
          multiline
          error={error_message}
        />
      </>
```
