### ISSUE TITLE
Dragging something non-draggable breaks everything in Firefox 45

### ISSUE THREAD

**Issue by SoonDead** [gaearon/react-dnd#313] opened 2015-10-25 12:54 UTC
Problem:
Certain user behaviour can break the scripts in Firefox 45 resulting in every drag operation throwing an error: `Error: Invariant Violation: Cannot call beginDrag while dragging.`

Steps to reproduce:
1. Visit any example on the [React DnD site](https://gaearon.github.io/react-dnd/), for example: https://gaearon.github.io/react-dnd/examples-sortable-simple.html
2. Try the example and see that is works properly.
3. Every example has the link "Browse the Source" above it, try dragging the link (but do not navigate away with it).
4. Try the example again and see that it does not work.
5. Check the console for the error mentioned above.

Not reproducable in FF 41, or in competing browsers.
In OSX it seems that only dragging stuff outside of the browser window breaks the script.

**Comment by gaearon** [comment] 2015-10-25 13:44
Would you like to try and help with this?

I usually put logs into the [HTML5 backend](https://github.com/gaearon/react-dnd-html5-backend) event handlers and see what's different in browsers and why.

**Comment by hedgerh** [comment] 2015-11-01 14:35
@SoonDead:  I'm unable to reproduce on a fresh copy of Firefox 41.0.2 on OSX.  Which version are you using?  I tried to reproduce in a few of the examples, including https://gaearon.github.io/react-dnd/examples-sortable-simple.html.

**Comment by SoonDead** [comment] 2015-11-01 17:11
Oh, sorry, it's probably important that I'm on FF 45 (nightly) on Windows.

**Comment by hedgerh** [comment] 2015-11-01 20:36
Alright.  I was able to reproduce on FF 45 on OS X.  Going to look into it.

@SoonDead, could you update your original post to reflect the following:
- To reproduce, drag any non-draggable element and drop it *outside the browser window.*
- Affects FF 45.  Not reproducible in FF 41, Chrome 46, or Safari 9.

**Comment by SoonDead** [comment] 2015-11-01 21:36
Not sure about needing to drag it outside the browser window. Here it seems to break on dragging anywhere.

**Comment by hedgerh** [comment] 2015-11-01 21:41
Yeah looks like it only does it when I drag outside the browser window on FF45 for OSX.  Which version of Windows are you rocking?

**Comment by SoonDead** [comment] 2015-11-02 08:09
Windows 10

**Comment by gaearon** [comment] 2015-11-03 00:14
I'm moving this issue to https://github.com/gaearon/react-dnd-html5-backend/issues/4, please continue the discussion there. It's not related to this repo.

**Closed by gaearon** 2015-11-03 00:14 UTC
Labels: bug

**Comment by gaearon** [comment] 2015-12-25 04:59
Should be fixed in `react-dnd-html5-backend@2.0.1`. Please verify.
