### ISSUE TITLE
acceptDrop is not called when there is over method

### ISSUE THREAD

**Issue by deser** [gaearon/react-dnd#35] opened 2015-01-26 13:53 UTC
In the example below acceptDrop is not called:

```js
configureDragDrop(registerType) {
        registerType(DndTypes.ITEM, {
            dragSource: {
                beginDrag() {
                    return {
                        item: {
                            id: this.props.id
                        }
                    };
                }
            },

            dropTarget: {
                over(item) {
                    this.props.moveCard(item.id, this.props.id);
                    return true;
                },

                acceptDrop() {
                    this.props.cardMoved();
                }
            }
        });
    },
```

**Comment by hakanderyal** [comment] 2015-01-26 13:58
If you are removing the item from DOM with `this.props.moveCard()`, `acceptDrop()` won't be called, as the item is unmounted, and the listeners are removed. ( You can check `DragDropMixin' to see what how things are wired)

As a workaround, I've added listeners to the `DragDropStore' from react-dnd on my parent component, and do the work there. 

I don't know if there are any other solutions to this.

**Comment by gaearon** [comment] 2015-01-26 17:16
>If you are removing the item from DOM with this.props.moveCard(), acceptDrop() won't be called, as the item is unmounted, and the listeners are removed. ( You can check `DragDropMixin' to see what how things are wired)

Are you sure this is the issue?
I just looked at the example, and the real issue seems to be that **we forbid dropping item on itself**.

I think this was a decision I took early on, and it might have been a wrong one. I don't remember why I did this now, and maybe it's worth re-evaulating it.

Specifically you can comment out [these lines](https://github.com/gaearon/react-dnd/blob/master/modules/mixins/DragDropMixin.js#L113-L115) in `DragDropMixin` to get the desired behavior:

```js
  getActiveDropTargetType() {
    var { draggedItemType, draggedItem, ownDraggedItemType } = this.state,
        dropTarget = this._dropTargets[draggedItemType];

    if (!dropTarget) {
      return null;
    }

    // if (draggedItemType === ownDraggedItemType) {
    //   return null;
    // }

    var { canDrop } = dropTarget;
    return canDrop(draggedItem) ? draggedItemType : null;
  },

```

**Comment by deser** [comment] 2015-01-26 21:20
Thanks guys! Can I suppose this issue will be fixed?

**Comment by gaearon** [comment] 2015-01-26 21:25
I'll release this tomorrow if I don't find issues with this approach.

**Comment by gaearon** [comment] 2015-01-27 19:02
Can you share more details about your use case?

The easiest way to do something after dragging is finished is in `endDrag` method of drag source:

```js
  configureDragDrop(registerType) {
    registerType(ItemTypes.CARD, {
      dragSource: {
        beginDrag() {
          return {
            item: {
              id: this.props.id
            }
          };
        },

        endDrag() {
          this.props.onCardMoved();
        }
      },

      dropTarget: {
        over(item) {
          this.props.moveCard(item.id, this.props.id);
        }
      }
    });
```

**Comment by gaearon** [comment] 2015-01-27 19:05
Also, there is no need for `over` to return `true`. We're handling HTML5 weirdness in mixin.

**Comment by deser** [comment] 2015-01-31 08:02
The point is that I have drop zone and it knows nothing about drag zones. Therefore I need acceptDrop to work properly.

**Comment by deser** [comment] 2015-01-31 08:02
Sorry for late answer

**Comment by gaearon** [comment] 2015-01-31 09:17
The only case when `acceptDrop` is not called, as far as I know, is when draggable and droppable is the same React component instance. The example code you attached is exactly this case. As I said, in this case it often makes more sense to handle `endDrag` to finalize, for example, sorting.

But this doesn't sound like what you're describing in your previous comment. `acceptDrop` should definitely fire if drag source and drop target are different components.

Can you share a sample project that reproduces your problem? You can also fork this one and tweak the examples.

If you can't, try putting a breakpoint in `DragDropMixin` somewhere before `acceptDrop` call and see why it's not firing.

**Comment by deser** [comment] 2015-01-31 14:05
OK, I'll see my code in a couple of days and reply you, thanks!

**Comment by gaearon** [comment] 2015-02-08 13:48
Closing this for now. Feel free to reopen if you have an example I can run.

**Closed by gaearon** 2015-02-08 13:48 UTC

**Comment by sebcante** [comment] 2015-02-17 04:16
hi @gaearon ,

sorry to comment on an old thread, are you still planning to remove the constraint to forbid dropping the item on it self ? ( `draggedItemType === ownDraggedItemType` ).

One of the use case  would be kanban UI (columns containing draggable cards)  where you can sort cards within the same column and/or dragdrop to a different column.

I am using the `over` callback to move the card on the client side but would love to use `acceptDrop`too  to commit this change to the server. At the moment (0.7.0) `acceptDrop` never gets called when sorting with the same list

thanks!

-seb

**Comment by nelix** [comment] 2015-02-17 12:27
@sebcante have you seen the sortable example?

**Comment by gaearon** [comment] 2015-02-17 12:48
@sebcante You should be able to sync with server in drag source's `endDrag`. It fires regardless of whether any drop target accepted the drop.

**Comment by sebcante** [comment] 2015-02-18 05:46
thanks guys, i ll give `endDrag` a go!

**Comment by gaearon** [comment] 2015-02-26 17:28
Superseded by #95
